# Generated by Django 5.2.3 on 2025-08-12 21:45

import django.db.models.deletion
import pdf_tool.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfUploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=pdf_tool.models.pdf_uploaded_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PDF Uploaded File (PDF Tool)',
                'verbose_name_plural': 'PDF Uploaded Files (PDF Tool)',
                'db_table': 'pdf_tool_uploaded_files',
            },
        ),
        migrations.CreateModel(
            name='PdfConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_format', models.CharField(choices=[('DOCX', 'DOCX'), ('JPG', 'JPG'), ('XLSX', 'XLSX'), ('PPTX', 'PPTX')], help_text='Desired output format (DOCX, JPG, XLSX, PPTX).', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the PDF conversion job.', max_length=20)),
                ('output_url', models.URLField(blank=True, help_text='URL to the processed PDF file (relative to MEDIA_URL).', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed message if the job failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_conversion_jobs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(help_text='The original PDF file uploaded for this conversion job.', on_delete=django.db.models.deletion.CASCADE, related_name='pdf_conversion_jobs', to='pdf_tool.pdfuploadedfile')),
            ],
            options={
                'verbose_name': 'PDF Conversion Job',
                'verbose_name_plural': 'PDF Conversion Jobs',
                'db_table': 'pdf_tool_conversion_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
