# Generated by Django 5.2.3 on 2025-08-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='target_format',
            field=models.CharField(choices=[('docx', 'docx'), ('jpg', 'jpg'), ('xlsx', 'xlsx'), ('pptx', 'pptx')], help_text='Desired output format (DOCX, JPG, XLSX, PPTX).', max_length=10),
        ),
    ]
