# Generated by Django 5.2.3 on 2025-08-14 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0002_alter_pdfconversionjob_target_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfuploadedfile',
            options={'verbose_name': 'PDF Tool Uploaded File', 'verbose_name_plural': 'PDF Tool Uploaded Files'},
        ),
        migrations.CreateModel(
            name='PdfToolJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('pdf_converter', 'PDF Converter'), ('file_compressor', 'File Compressor')], help_text='The type of operation to perform (e.g., pdf conversion or file compression).', max_length=50)),
                ('target_format', models.CharField(blank=True, choices=[('DOCX', 'DOCX'), ('XLSX', 'XLSX'), ('PPTX', 'PPTX'), ('JPG', 'JPG')], help_text='Desired output format for PDF conversion.', max_length=10, null=True)),
                ('compression_level', models.CharField(blank=True, choices=[('high', 'High Compression'), ('medium', 'Medium Compression'), ('low', 'Low Compression')], help_text='The desired compression level for PDF files.', max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the job.', max_length=20)),
                ('output_url', models.URLField(blank=True, help_text='URL to the processed file(s) (e.g., the converted DOCX or the ZIP archive).', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed message if the job failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_files', models.ManyToManyField(help_text='The file(s) uploaded for this job.', related_name='pdf_tool_jobs', to='pdf_tool.pdfuploadedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_tool_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Tool Job',
                'verbose_name_plural': 'PDF Tool Jobs',
                'db_table': 'pdf_tool_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PdfConversionJob',
        ),
    ]
