# Generated by Django 5.2.3 on 2025-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0003_alter_pdfuploadedfile_options_pdftooljob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftooljob',
            name='target_format',
            field=models.CharField(blank=True, choices=[('docx', 'docx'), ('xlsx', 'xlsx'), ('pptx', 'pptx'), ('jpg', 'jpg')], help_text='Desired output format for PDF conversion.', max_length=10, null=True),
        ),
    ]
