# Generated by Django 5.2.3 on 2025-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0004_alter_pdftooljob_target_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftooljob',
            name='merge_order',
            field=models.JSONField(blank=True, help_text="An ordered list of filenames to merge, e.g., ['file1.pdf', 'file2.pdf'].", null=True),
        ),
        migrations.AddField(
            model_name='pdftooljob',
            name='page_ranges',
            field=models.CharField(blank=True, help_text="Page ranges to extract, e.g., '1-5, 8, 10-12'.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdftooljob',
            name='output_url',
            field=models.URLField(blank=True, help_text='URL to the processed file(s).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pdftooljob',
            name='tool_type',
            field=models.CharField(choices=[('pdf_converter', 'PDF Converter'), ('file_compressor', 'File Compressor'), ('pdf_merger', 'PDF Merger'), ('pdf_splitter', 'PDF Splitter')], help_text='The type of operation to perform.', max_length=50),
        ),
    ]
